### ISSUE TITLE
[feature request] hook script to restart radvd when prefix is changed

### ISSUE THREAD

**Issue by bmeirellesRJ** [NetworkConfiguration/dhcpcd#124]
Hi friends,

can you do this for radvd.service when the prefix is changed?
I'm using the way below, but I don't know if it's the best way

/usr/lib/dhcpcd/dhcpcd-hooks/70-radvd.conf

case "$reason" in
(DELEGATED6)
/bin/systemctl restart radvd.service
exit 0
;;
esac

Thank you very much

**Comment by rsmarples** [comment]
Why do you need this? radvd is capable of listening to interface and address changes.
https://github.com/radvd-project/radvd/blob/master/netlink.c#L210

**Comment by bmeirellesRJ** [comment]
doesn't seem to work properly.

The provider provides dynamic prefix and changes it a few times a day.

when the prefix changes, it doesn't send the old prefix deprecation to the devices, even with this option enabled in radvd.conf , and the devices get too many addresses.

not even reloading radvd the prefix deprecation is sent. it is necessary to stop and start.

this problem is described here:
https://github.com/radvd-project/radvd/issues/91

**Comment by rsmarples** [comment]
Ouch, that sucks!

I do not want to put this into dhcpcd because restarting a RA service *will* cause it to announce that it's no longer a default router and *will* break existing connections to the outside.

One option, albiet a touch extreme, would be to put a decent RA server in to replace radvd - rtadvd that comes with the BSD platforms works well, but that does mean changing the OS and probably a touch overkill. But I can vouch for NetBSD being up to the task.

Another alternative would be something like this maybe?
https://mdlayher.com/blog/corerad-a-new-ipv6-router-advertisement-daemon/

It doesn't have the feature you need, but it has rudimentary netlink support and they might be able to put your feature request in.

**Comment by bmeirellesRJ** [comment]
Hi Roy,

I've been using debian for 15 years. I will try to corad. Thank you very much. Hugs
