### ISSUE TITLE
static ip address assignment

### ISSUE THREAD

**Issue by seamusdemora** [NetworkConfiguration/dhcpcd#164]
I'm trying to learn how (or if) `dhcpcd` assigns a CIDR value to a static IP address. I've reviewed some of the source code, but finding the answer that way looks to be a more difficult task than I'm up for at present. If the CIDR value is not specified in the `static` value assignment, does `dhcpcd`:

1. divine the value from a network query ?
2. assume a value; e.g. if a Class C IP addr is used, assume the CIDR is `/24` ?
3. some other method?

**Comment by maciej-napora** [comment]
I have the same question. I too looked at the source code. How this is done looks obscured.

**Comment by rsmarples** [comment]
`dhcpcd.conf.5` man page documents this here: https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/dhcpcd.conf.5.in#L682

Code to parse the option is here: https://github.com/NetworkConfiguration/dhcpcd/blob/master/src/if-options.c#L1110

If you don't specift a CIDR or netmask and there is no matching IP address on the interface to dervive it from then no netmask or CIDR is applied. We don't magically make one up.

Is the man page example not clear enough? If not, how can it be improved?

**Comment by maciej-napora** [comment]
Hi Roy, many thanks for answering that. A lot of people are using dhcpcd on their Raspberry Pi's, which is great. Some of them might be slow learners... I come from this camp.

 So, if I undertand correctly, when I have in dhcpcd.conf following lines:
`interface wlan0
static ip_address=192.168.0.1`

(Note that I have not provided CIDR.)

Then this function will be called:
https://github.com/NetworkConfiguration/dhcpcd/blob/4c97eb896bbb9a2b285efce2fa15aa9d2a9492d1/src/ipv4.c#L104

Which means the addr (dst) is in class C and netmask will be 255.255.255.0 (CIDR = 24)

As for the man page document provides an example for IP address with CIDR specified after /.  So one might wonder what happens if no CIDR is provided. But I think this thread here would clarify that.

Many thanks!

**Comment by seamusdemora** [comment]
@rsmarples : 

The example is crystal clear, although from the questions I've seen on RPi SE, most people miss the bit about `For IPv4, you should use the inform ipaddress option instead of setting a static address.`... they use `static` anyway. If RPi weren't using the oldie ver 8, I might suggest you put that sentence first, but there [doesn't seem to be much interest from the RPi org for changing the documentation.](https://github.com/raspberrypi/documentation/issues/2496) 

Sadly, the [Rpi org announced recently](https://www.raspberrypi.com/news/the-latest-update-to-raspberry-pi-os/) that they were dropping `dhcpcd` as the default DHCP client in favor of NetworkManager. I never understood the thinking on this; Debian stopped at ver 7, and RPi (a Debian derivative) stopped at ver 8. 

And thanks for your help on this question. @maciej-napora actually asked a question on RPi SE that prompted this. I thought I knew the answer, but wasn't clear on the how & why... turns out I was looking in the wrong source file :)

**Comment by rsmarples** [comment]
You know that a dhcpcd plugin for NetworkManager exists right?

**Comment by seamusdemora** [comment]
I had no idea actually!  What's it called?

**Comment by seamusdemora** [comment]
That's great. Is there any documentation or explanation of its function?

**Comment by rsmarples** [comment]
networkmanager.conf(5) says this:

```
dhcp=dhclient | dhcpcd
    This key sets up what DHCP client NetworkManager will use. Presently dhclient and dhcpcd are supported. The client configured here should be available on your system too. If this key is missing, available DHCP clients are looked for in this order: dhclient, dhcpcd. 
```

ArchLinux also has documentation here: https://wiki.archlinux.org/title/NetworkManager

Good luck!

**Comment by seamusdemora** [comment]
Thanks... sounds like I will need some good luck :)  

The first thing that amazed me was how compact the source code file was - a tiny fraction of `dhcpcd`. Next thing was the bit in the Arch-Linux docs that mentioned the `dhcpcd` option doesn't do IPv6. 

Hopefully, if the "Pi Masters" follow through with their announced switch from `dhcpcd` to  `nm`, they will leave the system in a state where restoring `dhcpcd` will be manageable. IIRC, RPi has used `dhcpcd` as long as I've used RPi... I've managed quite well with `dhcpcd`, and feel a bit like the rug is being pulled out from under my feet.

**Comment by rsmarples** [comment]
One of the wonders about Open Source is that you are never locked in.
I have a Steam Deck *(gets more playtime than my gaming rig, but I digress)*.
I can guarantee it doesn't run it's default DHCP client ;)
Everthing else is stock though .... not that crazy :D

But yes, the dhcpcd plugin is a lot smaller than the dhclient one the last I looked.
I'm discounting the internal dhcp client NM has because it's smaller as it's internal!

Anyway, just as a NetworkManager / DHCP / etc, dhcpcd is *still* the smallest **and** the only one that supports Linux, BSD, QNX and Solaris. It's also the most secure DHCP client.

**Comment by rsmarples** [comment]
So are we done here now? We can close this issue?

**Comment by seamusdemora** [comment]
Oh yeah  :)
