### ISSUE TITLE
Makefile:*: warning: ignoring prerequisites on suffix rule definition

### ISSUE THREAD

**Issue by perkelix** [NetworkConfiguration/dhcpcd#197]
Congratualtions on the dhcpcd-10 branch. 10.0.1. compiles very cleanly and runs smoothly. 

The only noticable output is some Makefile warnings (probably harmelss since they are marked as ignored). Please see the begining of the attached build log.
[dhcpcd_10.0.1-1_i386.build.txt](https://github.com/NetworkConfiguration/dhcpcd/files/11335819/dhcpcd_10.0.1-1_i386.build.txt)

**Comment by perkelix** [comment]
The part I was reporting about is in the ./configure segment at the start. There's several lines like this:

Makefile:*: warning: ignoring prerequisites on suffix rule definition

The warning about BPF is of course valid as well but, unless I'm mistaken, DHCP pretty much requires that sort of promiscuity to work at all?

**Comment by rsmarples** [comment]
`warning: ignoring prerequisites on suffix rule definition`

This is basically GNU saying they will force people to stop using BSD extensions to `make` and use GNU autoconf in the fullest - and it's apparently fine to use GNU extensions, because you know, GNU.

The only fix this will get is a comment that if GNU make ever stops working then use an older version or use bmake instead.
https://packages.debian.org/bookworm/bmake

> The warning about BPF is of course valid as well but, unless I'm mistaken, DHCP pretty much requires that sort of promiscuity to work at all?`

Yes it does. But on BSD we can supply a write filter and then tell the kernel it cannot be removed. So at most a compromised host can only send to the DHCP port and not just any port. We might add more restrictions in the future, but at least we can - on Linux we cannot.
