### ISSUE TITLE
DHCPv6 crashes Sonicwall firewall

### ISSUE THREAD

**Issue by AustrianSimon** [NetworkConfiguration/dhcpcd#233]
We have had spurious crashes of our Sonicwall perimeter firewall in the last few weeks, all related to DHCPv6. In an extensive debugging session we were finally able to capture the needed packet traces to identify the culprit, and it is the DHCPCD client (packet traces available if necessary). I am not clear why these crashes occur and what is different in the SOLICIT requests as I have no insight into the Sonicwall (older) 5.9.2.13-7o operating system. With a specific Linux variant (Raspi 4 Ubuntu Server 23.04, current RASPI Version) this crash occurred several times in a few minutes.

After I replaced the DHCPCD client with the ISC dhclient, no problem anymore and everything is working as advertized. Hence it is clear that some detail of the DHCPCD packets is crashing the firewall.

Is this problem perhaps known already and what can be done about it? Quite obviously, there is also a bug at the Sonicwall firmware, it should not crash on some unexpected packet detail.

**Comment by perkelix** [comment]
What dhcpcd version do you use?

**Comment by AustrianSimon** [comment]
So far I have identified two versions of dhcpcd that caused the crash:

The one that was included with Raspi3 and their Debian Linux distribution: dhcpcd version 6.7.1-1+rpi5
and the one included with Raspi4 and their Ubuntu 23.04 Server Linux distribution: dhcpcd version 9.4.1-19

I also suspect that dhcpcd version 7.1.0 (Ubuntu Server 22.04 for PCs) may have the same issue but never used it (the default of that install still was the isc client, which is why I didn't notice the firewall crashes).

**Comment by perkelix** [comment]
Versions older than 9 are deprecated. Please don't report bugs on these.

Among the versions you mention, 9.4.1 is the only relevant one. Let's focus on that one. Do you have any trace that would show what caused the crash?

**Comment by AustrianSimon** [comment]
Find the relevant trace attached, please.

The last few dhcpv6 packets (1 and 2) before the crash, packet 3 crashed the firewall, packet 4 is the first resend.

[sonicwall_crash_packet_trace.zip](https://github.com/NetworkConfiguration/dhcpcd/files/12225107/sonicwall_crash_packet_trace.zip)

**Comment by perkelix** [comment]
Thanks.

Just to check, are you in any position to build Debian/Ubuntu packages? I have a 9.5.2 that you could try. If that fixes it, we'll know that one of @rsmarples's recent cherry-picks since 9.4.1 does the trick. At that point, the only piece left is to figure out which one and, if necessary, to push a maintenance update to Debian, which would propagate to other derivatives.

**Comment by AustrianSimon** [comment]
Unfortunately I am currently not in a position to build the package.

I am fairly sure the problem was introduced in or before version 7, hence the problem will be present in all 9 versions, too. It could well be some flag in the request, or some option in the request, which go beyond what ISC has implemented.

I did not find any possibility in the configuration to limit the behaviour of dhcpcd to a set of known options/flags and not permit flags/options/features that go beyond the reference ISC (which would solve the issue).

**Comment by perkelix** [comment]
What we need is an strace of the crash, not an Ethernet capture.

**Comment by AustrianSimon** [comment]
You mean of the sonicwall firewall, their internal crash trace (like to be submitted to Sonicwall)?

For comparison, here's a packet capture of the DHCPv6 exchanges that was done from Raspi4 after removing dhcpcd and replacing it with isc. For example, this request does not include a couple of options like SOL_MAX_RT and INF_MAX_RT (I didn't check yet for other differences, the DUIDs are different but it is the same device).

What I did notice with the dhcpcd client: the DUID although being defined as link-layer-time did NOT reflect the link-layer (MAC: d8:3a:dd:25:46:85) with its dhcpcd DUID 000100011edaf105b827ebdacf27, only the ISC then produced a correct llt DUID.

[sonicwall_nocrash_packet_trace.zip](https://github.com/NetworkConfiguration/dhcpcd/files/12225413/sonicwall_nocrash_packet_trace.zip)

**Comment by rsmarples** [comment]
So in your packet capture we can we that you are using dhcpcd-6.7.1
There is nothing technically wrong with the DHCPv6 packets it sends either - the latest wireshark finds no problems with it them.
So any sonicwall crash trying to read it needs to be fixed by sonciwall?

The DUID reflects *a* link layer that dhcpcd found installed at the time noted.
It does not have to reflect the link layer actually used for transmission.
You can regenerate the duid file by stopping dhcpcd, removing the file  /var/db/dhcpcd.duid and restarting dhcpcd.
If you start dhcpcd for a specific interface it will use that interfaces MAC to generate the DUID, otherwise it will use the first interface with a MAC it finds.

dhcpcd-6.7.1 is unsupported by me as it's far to old to maintain, please upgrade to something more modern.
