### ISSUE TITLE
Clarification re. allowinterfaces / denyinterfaces

### ISSUE THREAD

**Issue by gadall** [NetworkConfiguration/dhcpcd#350]
With `allowinterfaces ppp0` in the configuration file, if dhcpcd is started when `ppp0` doesn't exist, it only says `no valid interfaces found` and then it does nothing when `ppp0` does appear.

If no allowed or denied interfaces are defined, or if at least one allowed interface exists during startup, `ppp0` can come and go freely and everything works.

Anyway, I don't really understand what is the intended purpose of these options. It intuitively makes sense to restrict operations to where they are needed but a more specific explanation would be welcome.

It seems that if one wants to restrict dhcpcd to an interface that comes and goes, dhcpcd must be configured to start and stop with the interface, rather than run always in the background.

Thanks!

**Comment by rsmarples** [comment]
This should be fixed in 21e3dbf97 and will be in the next dhcpcd release.
You could verify by testing the master branch from git.

**Comment by gadall** [comment]
Is that the right commit?

**Comment by rsmarples** [comment]
Maybe it is as it affects PPP interfaces coming and going. But there could be other commits in play as well.

I cannot replicate this using the master branch and having a PPPoE interface coming and going.
However, from your description it sounds more like a config inside dhcpcd rather than this.
Anyway, can you please test the master branch and if that fails to work can you attach your full dhcpcd.conf please?

**Comment by gadall** [comment]
@rsmarples I just realized I was indeed not running the latest code. A few days ago I did a dist-upgrade and I didn't notice debian published a new package, which got installed, effectively downgrading.
Indeed there's no issue on git master.
So sorry!

**Comment by rsmarples** [comment]
dhcpcd-10.0.9 is now out, so this is good :)
