### ISSUE TITLE
dhcpcd loses static IP 

### ISSUE THREAD

**Issue by rlyons20** [NetworkConfiguration/dhcpcd#36]
I have been using a Pi-hole(s) at home for years now.

Last year I upgrade to Raspberry Pi 4 hardware, and noticed that the Pi-hole would become unavailable sporadically. When it was unavailable, it would be hard down. No response to ping. The only resolution was to power cycle it.

I started to think it was a problem with the new hardware, so I switched to a Pi Zero, and had the same problem. I recently moved to a temporary house, and set up a Pi-hole here on an old Raspberry Pi 3b+ that I had laying around, and I'm having the same problem here.

So, I started Splunking the Pi-hole, and noticed that every time the problem occurs, a device comes onto the network, and a message like this is logged on the system:
`Apr 26 19:42:45 pi-hole dhcpcd[547]: eth0: hardware address xx:xx:xx:xx:xx:xx claims 192.168.1.250`

The forums for pi-hole, raspberry pi and OnePlus all have several complaints about similar issues.  Some people are suggesting ARP poisoning, others claim version problems with dhcpcd.

I don't claim to know the root cause, but the problem is persistent.  Basically, every time I come home now, the Pi-hole goes dead.

Please help!

**Comment by rsmarples** [comment]
The problem on the PiHole forum was that a router was L2 unicasting to dhcpcd an ARP probe for the address but with all hardware addresses in the ARP message at zero.
I added commit 9b62df5ad53d251d9cf0ecbe8571ae9262e8bde0 to help with this issue by logging the L2 sender address as well.
Based on your message you don't have this change and thus using dhcpcd-8 or older.

If you upgrade to dhcpcd-9.x *(9.4.0 is the latest release)* then you will get a better diagnostic message at least. It's unlikely to fix your problem though because there are no relevant changes in the ARP code in dhcpcd since adding the new diagnostic.

As such it's very likely that something on your network is either sending faulty ARP probes (as in the original PiHole problem report) or something is really trying to use your address. You can tell dhcpcd to not use ARP by adding `noarp` to `/etc/dhcpcd.conf` - this will disable Duplicate Address Detection for IPv4 addresses and work around your problem.

**Comment by rlyons20** [comment]
You are correct!  I'm using v8.1.2.  I'm going to see if I can upgrade to the latest ver

I completely agree about the faulty ARP probes.  In every case, it's an Android phone, and I am not at all surprised that Android devices would misbehave :)

I also found someone having similar problems who used noarp, so i added that setting a few days ago.  So far, so good!

Thank you so much for the response!

**Comment by rsmarples** [comment]
Closing as seems resolved.

**Comment by lytedev** [comment]
> Adding noarp fixed the problem.

Dude, thank you. This fixed my whole home network when my brother, who has a OnePlus device came to visit and suddenly everything was broken. I read your comment and my jaw dropped and things fixed right away. Pretty wild.
