### ISSUE TITLE
Infinite loop with DHCP Inform option

### ISSUE THREAD

**Issue by klanmiko** [NetworkConfiguration/dhcpcd#47]
Hi. This issue relates to symptoms found in [this RPi thread](https://www.raspberrypi.org/forums/viewtopic.php?t=265516)

In my own testing, on dhcpcd 9.4.0, running dhcpcd from the command line like:`dhcpcd -B -s 10.10.10.3/24 eth0` does cause the syslog to be filled with messages like: 
Aug 16 14:56:49 meraki dhcpcd[361]: eth0: received approval for 10.10.10.3
Aug 16 14:56:49 meraki dhcpcd[361]: eth0: received approval for 10.10.10.3
Aug 16 14:56:49 meraki dhcpcd[361]: eth0: received approval for 10.10.10.3

In addition, the device sends repeated DHCPINFORM (and ARP announcements) at a high frequency.

I did some debugging and it seems that with the first DHCP ACK, `dhcp_bind` calls `ipv4_applyaddr` which adds the address to the kernel. There is a handler for the kernel response `dhcp_handleifa` which calls `dhcp_inform` again, continuing the cycle.

Another phenomena I have noticed is that future DHCP ACKS are processed both by the newly opened UDP socket and the bpf filter, which keeps getting closed by dhcp_bind and reopened by dhcp_inform

I will try to contribute a fix but I would appreciate help solving this in a way that won't introduce a regression, since I am not familiar with dhcpcd's code.

**Comment by seamusdemora** [comment]
Hello - I've just found this while searching the cause of the 8/second log entries I see when using the recommended `inform <ipv4 addr>` option (instead of `static ip`; i.e.

```
# edit /etc/dhcpcd.conf; added 2 lines
# interface wlan0
# inform 192.168.1.199/24
```

After save & reboot:

```
$ journalctl -f | grep wlan0
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
Mar 26 07:15:17 raspberrypi0w dhcpcd[568]: wlan0: received approval for 192.168.1.199
```

Pleased to see you've already patched this, but surprised to see that the latest available ver of `dhcpcd` in RPi OS bullseye is:

```
$ dhcpcd --version
dhcpcd 8.1.2
Copyright (c) 2006-2019 Roy Marples
Compiled in features: INET ARP ARPing IPv4LL INET6 DHCPv6 AUTH
``` 

Couple of questions maybe you can answer: 
1. Any idea why RPi is so far behind? 8.1.2 ==> 9.4.0 seems *far behind*.
2. Any chance of pushing your changes to an earlier (downstream?) version?? 

Please also note this is also related to a [discussion of an issue I opened re RPi OS documentation](https://github.com/raspberrypi/documentation/issues/2496). 

Thnx 4 all,
~S
